---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: xk6-loki-read
  namespace: load-test
spec:
  parallelism: 4
  script:
    configMap: 
      name: read-senario
      file: read-senario.js
  runner:
    image: docker.io/7777ksh/xk6-loki:7.0.1
    env:
    - name: BASE_URL
      value: "http://loki-gateway.snappcloud-network-logging.svc.cluster.local"
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: xk6-loki-write
  namespace: load-test
spec:
  parallelism: 4
  script:
    configMap: 
      name: write-senario
      file: write-senario.js
  runner:
    image: docker.io/7777ksh/xk6-loki:7.0.1
    env:
    - name: BASE_URL
      value: "http://loki-gateway.snappcloud-network-logging.svc.cluster.local" 
